# 公共配置

# 可靠事件组件 commander 需要的配置
spring:
  rabbitmq:
    addresses: "172.16.18.5:5672,172.16.18.6:5672,172.16.18.7:5672"
    username: "admin"
    password: "rabbitmq"
    virtual-host: "xjs_host_qa"
  jpa:
    generate-ddl: false    # 让jpa不要在启动时自动根据entity创建表
    show-sql: false
    hibernate:
      ddl-auto: none       # 让 hibernate 不要在启动时删除、创建表

  datasource:
    platform: h2
    schema:
    - classpath:commander.client.schema.h2.sql
    
logging:
  level:
    org.hibernate: info
    # 显示 sql 语句的参数
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.hibernate.type.descriptor.sql.BasicExtractor: info
    com.huajin.commander: debug
# 结束"可靠事件"组件 commander 的配置
