server:
  port: 8030
  
spring:
  application:
    name: reliable-event-manager
  jpa:
    generate-ddl: false    # 让jpa不要在启动时自动根据entity创建表
    show-sql: false        # 会将SQL打印到标准输出
    hibernate:
      ddl-auto: none       # 让 hibernate 不要在启动时删除、创建表
  datasource:
    platform: h2
    schema:
    - classpath:schema.h2.sql
  rabbitmq:
    addresses: "172.16.18.5:5672,172.16.18.6:5672,172.16.18.7:5672"
    username: "admin"
    password: "rabbitmq"
    virtual-host: "xjs_host_qa"
    listener:
      retry:
        enabled: true # 避免抛异常时死循环
        multiplier: 2 # 每次间隔时间增大2倍
        
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
      healthcheck:
        enable: true

logging:
  level:
    root: info
    org.hibernate: error
    # 显示 sql 语句的参数
    org.hibernate.type.descriptor.sql.BasicBinder: info     # SQL参数
    org.hibernate.type.descriptor.sql.BasicExtractor: info  # SQL返回值
    # 应用日志级别
    com.huajin.commander: debug

